apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ required "Please set a storageClass" .Values.storageClass }}
  resources:
    requests:
      storage: 1Gi
